package src.db;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

public class SchemaInitializer
{
    private SchemaInitializer() {};

    public static void initialize()
    {
        try (Connection conn = DBConnection.getConnection())
        {
            Statement stmt = conn.createStatement();

            // Khởi tạo bảng users
            stmt.execute("""
                    CREATE TABLE IF NOT EXISTS users (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        email VARCHAR(100) NOT NULL UNIQUE,
                        fullname VARCHAR(100) NOT NULL,
                        password_hash VARCHAR(255) NOT NULL,
                        role VARCHAR(20) NOT NULL,
                        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        CONSTRAINT chk_user_role CHECK (role IN ('ADMIN','SELLER','BIDDER'))
                    )
                    """);

            // Khởi tạo bảng items
            stmt.execute("""
                    CREATE TABLE IF NOT EXISTS items (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        seller_id BIGINT NOT NULL,
                        seller_email VARCHAR(100) NOT NULL,
                        type VARCHAR(50) NOT NULL,
                        name VARCHAR(100) NOT NULL,
                        description VARCHAR(500),
                        starting_bid DECIMAL(19,2) NOT NULL,
                        img_url VARCHAR(255),
                        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        CONSTRAINT fk_items_seller FOREIGN KEY (seller_id) REFERENCES users(id)
                    )
                    """);
                    
            System.out.println("Schema initialized successfully");
        } catch (SQLException e) {
            System.err.println("Error initializing schema: " + e.getMessage());
            e.printStackTrace();
        }
    }

    public static void main(String[] args)
    {
        SchemaInitializer.initialize();
    }
}
