package com.ltnc.auction.server.service;

import com.ltnc.auction.server.dao.AuctionDAO;
import com.ltnc.auction.server.dao.AutoBidDAO;
import com.ltnc.auction.server.dao.BidDAO;
import com.ltnc.auction.server.dao.UserDAO;
import com.ltnc.auction.server.dao.WalletDAO;
import com.ltnc.auction.server.dao.WalletTransactionDAO;
import com.ltnc.auction.server.model.Admin;
import com.ltnc.auction.server.model.Auction;
import com.ltnc.auction.server.model.Bidder;
import com.ltnc.auction.server.model.User;
import com.ltnc.auction.server.model.Wallet;
import com.ltnc.auction.server.model.WalletTransaction;
import com.ltnc.auction.server.service.AuctionService.BidResult;
import com.ltnc.auction.server.service.AuctionService.BidResultCode;
import com.ltnc.auction.server.service.WalletService;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;

import java.lang.reflect.Field;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.atomic.AtomicInteger;

import static org.junit.jupiter.api.Assertions.*;

@TestInstance(TestInstance.Lifecycle.PER_CLASS)
public class AuctionServiceTest {

    private static final String TEST_DB_URL = "jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1";
    private AuctionService auctionService;
    private AuctionDAO auctionDAO;
    private BidDAO bidDAO;

    @BeforeAll
    void setupDatabase() throws Exception {
        // Override DBConnection to use in-memory test DB
        // We do this by intercepting the connection via a static initializer trick
        // For testing, we initialize the schema directly using the test DB URL
        try (Connection conn = DriverManager.getConnection(TEST_DB_URL, "sa", "");
             Statement stmt = conn.createStatement()) {
            stmt.execute("""
                CREATE TABLE IF NOT EXISTS users (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    username VARCHAR(100) UNIQUE,
                    full_name VARCHAR(100),
                    password_hash VARCHAR(255),
                    role VARCHAR(20)
                )
                """);
            stmt.execute("""
                CREATE TABLE IF NOT EXISTS items (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    seller_id BIGINT,
                    seller_email VARCHAR(100),
                    type VARCHAR(20),
                    name VARCHAR(200),
                    description VARCHAR(1000),
                    starting_bid DECIMAL(19,2),
                    image_url VARCHAR(500)
                )
                """);
            stmt.execute("""
                CREATE TABLE IF NOT EXISTS auctions (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    item_id BIGINT,
                    title VARCHAR(200),
                    description VARCHAR(1000),
                    category VARCHAR(50),
                    starting_bid DECIMAL(19,2),
                    current_bid DECIMAL(19,2),
                    start_time TIMESTAMP,
                    end_time TIMESTAMP,
                    status VARCHAR(20),
                    highest_bidder_id BIGINT,
                    winner_email VARCHAR(100),
                    seller_email VARCHAR(100),
                    image_url VARCHAR(500)
                )
                """);
            stmt.execute("""
                CREATE TABLE IF NOT EXISTS bid_transactions (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    auction_id BIGINT,
                    bidder_id BIGINT,
                    bidder_email VARCHAR(100),
                    bidder_name VARCHAR(100),
                    amount DECIMAL(19,2),
                    created_at TIMESTAMP
                )
                """);
            stmt.execute("""
                CREATE TABLE IF NOT EXISTS auto_bid_configs (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    auction_id BIGINT,
                    bidder_id BIGINT,
                    bidder_email VARCHAR(100),
                    max_bid DECIMAL(19,2),
                    increment_amount DECIMAL(19,2),
                    registered_at TIMESTAMP,
                    UNIQUE(auction_id, bidder_id)
                )
                """);

            // Seed test users
            stmt.execute("MERGE INTO users (username, full_name, password_hash, role) KEY(username) " +
                "VALUES ('bidder1@test.com', 'Bidder One', 'hash1', 'BIDDER')");
            stmt.execute("MERGE INTO users (username, full_name, password_hash, role) KEY(username) " +
                "VALUES ('bidder2@test.com', 'Bidder Two', 'hash2', 'BIDDER')");
        }
    }

    @BeforeEach
    void setup() throws Exception {
        Field wsInstance = WalletService.class.getDeclaredField("instance");
        wsInstance.setAccessible(true);
        wsInstance.set(null, null);
        WalletService walletService = WalletService.getInstance();
        Field walletDaoField = WalletService.class.getDeclaredField("walletDAO");
        walletDaoField.setAccessible(true);
        walletDaoField.set(walletService, new StubWalletDAO());
        Field walletTxField = WalletService.class.getDeclaredField("txDAO");
        walletTxField.setAccessible(true);
        walletTxField.set(walletService, new StubWalletTxDAO());

        // Reset the AuctionService singleton for each test
        Field instanceField = AuctionService.class.getDeclaredField("instance");
        instanceField.setAccessible(true);
        instanceField.set(null, null);

        auctionService = AuctionService.getInstance();

        // Use in-memory test DAO instances via reflection
        auctionDAO = new TestAuctionDAO();
        bidDAO = new TestBidDAO();

        Field auctionDAOField = AuctionService.class.getDeclaredField("auctionDAO");
        auctionDAOField.setAccessible(true);
        auctionDAOField.set(auctionService, auctionDAO);

        Field bidDAOField = AuctionService.class.getDeclaredField("bidDAO");
        bidDAOField.setAccessible(true);
        bidDAOField.set(auctionService, bidDAO);

        Field userDAOField = AuctionService.class.getDeclaredField("userDAO");
        userDAOField.setAccessible(true);
        userDAOField.set(auctionService, new TestUserDAO());

        Field autoBidDAOField = AuctionService.class.getDeclaredField("autoBidDAO");
        autoBidDAOField.setAccessible(true);
        autoBidDAOField.set(auctionService, new TestAutoBidDAO());

        Field broadcastField = BroadcastManager.class.getDeclaredField("instance");
        broadcastField.setAccessible(true);
        broadcastField.set(null, null);
    }

    @Test
    void placeBid_insufficientFunds() throws Exception {
        WalletService ws = WalletService.getInstance();
        Field walletDaoField = WalletService.class.getDeclaredField("walletDAO");
        walletDaoField.setAccessible(true);
        walletDaoField.set(ws, new StubWalletDAO(new BigDecimal("10.00")));

        Auction auction = createRunningAuction(99L, 100.0, 3600);
        BidResult result = auctionService.placeBid(99L, "bidder1@test.com", 150.0);

        assertEquals(BidResultCode.INSUFFICIENT_FUNDS, result.code());
        assertNotNull(result.requiredTopUp());
        assertTrue(result.requiredTopUp() > 0);
    }

    private Auction createRunningAuction(Long id, double startingBid, int endInSeconds) throws Exception {
        Auction auction = new Auction();
        auction.setId(id);
        auction.setTitle("Test Auction " + id);
        auction.setDescription("Test");
        auction.setCategory("Electronics");
        auction.setStartingBid(BigDecimal.valueOf(startingBid));
        auction.setCurrentBid(BigDecimal.valueOf(startingBid));
        auction.setStartTime(LocalDateTime.now().minusMinutes(5));
        auction.setEndTime(LocalDateTime.now().plusSeconds(endInSeconds));
        auction.setStatus("RUNNING");
        auction.setSellerEmail("seller@test.com");

        // Inject into activeAuctions map via reflection
        Field activeField = AuctionService.class.getDeclaredField("activeAuctions");
        activeField.setAccessible(true);
        ConcurrentHashMap<Long, Auction> activeAuctions = (ConcurrentHashMap<Long, Auction>) activeField.get(auctionService);
        activeAuctions.put(id, auction);

        return auction;
    }

    @Test
    void placeBid_ok_when_amount_higher() throws Exception {
        Auction auction = createRunningAuction(1L, 100.0, 3600);

        BidResult result = auctionService.placeBid(1L, "bidder1@test.com", 150.0);

        assertEquals(BidResultCode.OK, result.code());
        assertNotNull(result.auction());
        assertEquals(150.0, result.auction().currentBid, 0.01);
    }

    @Test
    void placeBid_fails_bid_too_low() throws Exception {
        Auction auction = createRunningAuction(2L, 100.0, 3600);

        BidResult result = auctionService.placeBid(2L, "bidder1@test.com", 50.0);

        assertEquals(BidResultCode.BID_TOO_LOW, result.code());
    }

    @Test
    void placeBid_fails_when_increment_less_than_ten() throws Exception {
        Auction auction = createRunningAuction(101L, 100.0, 3600);

        // Place a valid initial bid of 110.0
        BidResult res1 = auctionService.placeBid(101L, "bidder1@test.com", 110.0);
        assertEquals(BidResultCode.OK, res1.code());

        // Now place a bid of 115.0 (which is only $5 higher than 110.0) -> should fail
        BidResult res2 = auctionService.placeBid(101L, "bidder2@test.com", 115.0);
        assertEquals(BidResultCode.BID_TOO_LOW, res2.code());

        // Now place a bid of 120.0 (which is $10 higher than 110.0) -> should succeed
        BidResult res3 = auctionService.placeBid(101L, "bidder2@test.com", 120.0);
        assertEquals(BidResultCode.OK, res3.code());
    }

    @Test
    void placeBid_fails_when_auction_not_running() throws Exception {
        Auction auction = createRunningAuction(3L, 100.0, 3600);
        auction.setStatus("FINISHED");

        BidResult result = auctionService.placeBid(3L, "bidder1@test.com", 200.0);

        assertEquals(BidResultCode.AUCTION_CLOSED, result.code());
    }

    @Test
    void antiSniping_extends_endTime() throws Exception {
        // Auction ends in 10 seconds (within 30s window)
        Auction auction = createRunningAuction(4L, 100.0, 10);
        LocalDateTime originalEndTime = auction.getEndTime();

        BidResult result = auctionService.placeBid(4L, "bidder1@test.com", 150.0);

        assertEquals(BidResultCode.OK, result.code());
        // EndTime should be extended by 60 seconds
        assertTrue(auction.getEndTime().isAfter(originalEndTime));
        assertTrue(auction.getEndTime().isAfter(originalEndTime.plusSeconds(50)));
    }

    @Test
    void autoBid_skipped_when_bot_wallet_insufficient() throws Exception {
        WalletService ws = WalletService.getInstance();
        Field walletDaoField = WalletService.class.getDeclaredField("walletDAO");
        walletDaoField.setAccessible(true);
        walletDaoField.set(ws, new StubWalletDAO() {
            @Override
            public Wallet findOrCreateByUserId(Long userId) {
                if (Long.valueOf(2L).equals(userId)) {
                    Wallet w = new Wallet();
                    w.setUserId(2L);
                    w.setBalance(new BigDecimal("120.00"));
                    w.setReserved(BigDecimal.ZERO);
                    return w;
                }
                return super.findOrCreateByUserId(userId);
            }
        });

        Auction auction = createRunningAuction(60L, 100.0, 3600);
        auctionService.registerAutoBid(60L, "bidder2@test.com", 300.0, 50.0);

        BidResult result = auctionService.placeBid(60L, "bidder1@test.com", 150.0);

        assertEquals(BidResultCode.OK, result.code());
        assertEquals(150.0, auction.getCurrentBid().doubleValue(), 0.01);
    }

    @Test
    void registerAutoBid_validation() throws Exception {
        Auction auction = createRunningAuction(70L, 100.0, 3600);

        // 1. Valid registration
        boolean ok1 = auctionService.registerAutoBid(70L, "bidder1@test.com", 150.0, 10.0);
        assertTrue(ok1);

        // 2. Max bid too low (less than or equal to current price of 100)
        boolean ok2 = auctionService.registerAutoBid(70L, "bidder1@test.com", 100.0, 10.0);
        assertFalse(ok2);
        boolean ok3 = auctionService.registerAutoBid(70L, "bidder1@test.com", 90.0, 10.0);
        assertFalse(ok3);

        // 3. Step/increment <= 0
        boolean ok4 = auctionService.registerAutoBid(70L, "bidder1@test.com", 150.0, 0.0);
        assertFalse(ok4);
        boolean ok5 = auctionService.registerAutoBid(70L, "bidder1@test.com", 150.0, -5.0);
        assertFalse(ok5);
    }

    @Test
    void autoBid_triggers_when_outbid() throws Exception {
        Auction auction = createRunningAuction(5L, 100.0, 3600);

        // Register auto-bid for bidder2 with max 300, increment 50
        auctionService.registerAutoBid(5L, "bidder2@test.com", 300.0, 50.0);

        // bidder1 places bid of 150
        BidResult result = auctionService.placeBid(5L, "bidder1@test.com", 150.0);

        assertEquals(BidResultCode.OK, result.code());
        // Auto-bid should have fired: 150 + 50 = 200
        assertEquals(200.0, auction.getCurrentBid().doubleValue(), 0.01);
    }

    @Test
    void placeBid_increments_broadcast_counters() throws Exception {
        BroadcastManager bm = BroadcastManager.getInstance();
        long cAllBefore = bm.getBroadcastAllCount();
        long cUserBefore = bm.getBroadcastUserCount();

        Auction auction = createRunningAuction(50L, 100.0, 3600);
        BidResult result = auctionService.placeBid(50L, "bidder1@test.com", 175.0);

        assertEquals(BidResultCode.OK, result.code());
        assertTrue(bm.getBroadcastAllCount() > cAllBefore);
        assertTrue(bm.getBroadcastUserCount() > cUserBefore);
    }

    @Test
    void concurrency_fifty_threads_highest_bid_wins() throws Exception {
        Auction auction = createRunningAuction(51L, 100.0, 3600);

        int threadCount = 50;
        ExecutorService executor = Executors.newFixedThreadPool(threadCount);
        CountDownLatch latch = new CountDownLatch(threadCount);

        for (int i = 0; i < threadCount; i++) {
            double bidAmount = 150.0 + i * 10;
            executor.submit(() -> {
                try {
                    auctionService.placeBid(51L, "bidder1@test.com", bidAmount);
                } finally {
                    latch.countDown();
                }
            });
        }

        latch.await();
        executor.shutdown();

        assertEquals(640.0, auction.getCurrentBid().doubleValue(), 1.0);
        WalletService ws = WalletService.getInstance();
        Wallet w = ws.getWallet(1L);
        assertTrue(w.getReserved().compareTo(java.math.BigDecimal.ZERO) >= 0);
    }

    @Test
    void concurrentBids_no_lost_update() throws Exception {
        Auction auction = createRunningAuction(6L, 100.0, 3600);

        int threadCount = 10;
        ExecutorService executor = Executors.newFixedThreadPool(threadCount);
        CountDownLatch latch = new CountDownLatch(threadCount);
        AtomicInteger successCount = new AtomicInteger(0);

        for (int i = 0; i < threadCount; i++) {
            final double bidAmount = 200.0 + i * 10;
            executor.submit(() -> {
                try {
                    BidResult result = auctionService.placeBid(6L, "bidder1@test.com", bidAmount);
                    if (result.code() == BidResultCode.OK) {
                        successCount.incrementAndGet();
                    }
                } finally {
                    latch.countDown();
                }
            });
        }

        latch.await();
        executor.shutdown();

        // At least some bids should succeed; current bid should be the highest valid bid
        assertTrue(successCount.get() >= 1);
        assertTrue(auction.getCurrentBid().doubleValue() >= 200.0);
        // The bid list should be consistent (no negative bids, no duplicates of same amount from race)
        assertFalse(auction.getBids().isEmpty());
    }

    @Test
    void placeBid_rollsBack_onDatabaseException() throws Exception {
        Auction auction = createRunningAuction(88L, 100.0, 3600);

        Field bidDAOField = AuctionService.class.getDeclaredField("bidDAO");
        bidDAOField.setAccessible(true);
        bidDAOField.set(auctionService, new TestBidDAO() {
            @Override
            public Long insert(com.ltnc.auction.server.model.BidTransaction bid) {
                try {
                    WalletService ws = WalletService.getInstance();
                    Field walletDaoField = WalletService.class.getDeclaredField("walletDAO");
                    walletDaoField.setAccessible(true);
                    Object stubWalletDAO = walletDaoField.get(ws);
                    ((StubWalletDAO) stubWalletDAO).updateBalances(1L, new BigDecimal("100000.00"), BigDecimal.ZERO);
                } catch (Exception ignored) {}
                throw new RuntimeException("Simulated Database Failure");
            }
        });

        WalletService ws = WalletService.getInstance();
        Wallet initialWallet = ws.getWallet(1L);
        BigDecimal initialReserved = initialWallet.getReserved();
        BigDecimal initialBalance = initialWallet.getBalance();

        assertThrows(RuntimeException.class, () -> {
            auctionService.placeBid(88L, "bidder1@test.com", 150.0);
        });

        assertEquals(100.0, auction.getCurrentBid().doubleValue(), 0.01);
        assertNull(auction.getHighestBidderId());

        Wallet finalWallet = ws.getWallet(1L);
        assertEquals(initialReserved, finalWallet.getReserved());
        assertEquals(initialBalance, finalWallet.getBalance());
    }

    // ---- Test DAO Implementations (simple in-memory stubs) ----

    static class StubWalletDAO extends WalletDAO {
        private final ConcurrentHashMap<Long, Wallet> map = new ConcurrentHashMap<>();
        private final BigDecimal initialBalance;

        StubWalletDAO() {
            this(new BigDecimal("100000.00"));
        }

        StubWalletDAO(BigDecimal initialBalance) {
            this.initialBalance = initialBalance;
            Wallet w1 = new Wallet();
            w1.setUserId(1L);
            w1.setBalance(initialBalance);
            w1.setReserved(BigDecimal.ZERO);
            map.put(1L, w1);
            Wallet w2 = new Wallet();
            w2.setUserId(2L);
            w2.setBalance(initialBalance);
            w2.setReserved(BigDecimal.ZERO);
            map.put(2L, w2);
        }

        @Override
        public Wallet findByUserId(Long userId) {
            return map.get(userId);
        }

        @Override
        public Wallet findOrCreateByUserId(Long userId) {
            return map.computeIfAbsent(userId, id -> {
                Wallet w = new Wallet();
                w.setUserId(id);
                w.setBalance(initialBalance);
                w.setReserved(BigDecimal.ZERO);
                return w;
            });
        }

        @Override
        public void updateBalances(Long userId, BigDecimal balance, BigDecimal reserved) {
            Wallet w = findOrCreateByUserId(userId);
            w.setBalance(balance);
            w.setReserved(reserved);
            map.put(userId, w);
        }
    }

    static class StubWalletTxDAO extends WalletTransactionDAO {
        @Override
        public Long insert(WalletTransaction tx) {
            return 1L;
        }
    }

    static class TestAuctionDAO extends AuctionDAO {
        private final ConcurrentHashMap<Long, Auction> store = new ConcurrentHashMap<>();
        private long nextId = 100;

        @Override
        public Long insert(Auction auction) {
            long id = nextId++;
            auction.setId(id);
            store.put(id, auction);
            return id;
        }

        @Override
        public boolean updateCurrentBid(Long auctionId, java.math.BigDecimal newBid, Long highestBidderId) {
            Auction a = store.get(auctionId);
            if (a != null) {
                a.setCurrentBid(newBid);
                a.setHighestBidderId(highestBidderId);
            }
            return true;
        }

        @Override
        public boolean updateStatus(Long auctionId, String status, String winnerEmail) {
            Auction a = store.get(auctionId);
            if (a != null) {
                a.setStatus(status);
                a.setWinnerEmail(winnerEmail);
            }
            return true;
        }

        @Override
        public boolean updateEndTime(Long auctionId, LocalDateTime newEndTime) {
            Auction a = store.get(auctionId);
            if (a != null) {
                a.setEndTime(newEndTime);
            }
            return true;
        }

        @Override
        public Auction findById(Long id) {
            return store.get(id);
        }

        @Override
        public List<Auction> findAll() {
            return new ArrayList<>(store.values());
        }

        @Override
        public List<Auction> findByStatus(String status) {
            return store.values().stream()
                    .filter(a -> status.equals(a.getStatus()))
                    .collect(java.util.stream.Collectors.toList());
        }
    }

    static class TestBidDAO extends BidDAO {
        private long nextId = 1000;

        @Override
        public Long insert(com.ltnc.auction.server.model.BidTransaction bid) {
            long id = nextId++;
            bid.setId(id);
            return id;
        }

        @Override
        public List<com.ltnc.auction.server.model.BidTransaction> findByAuction(Long auctionId) {
            return new ArrayList<>();
        }

        @Override
        public List<com.ltnc.auction.server.model.BidTransaction> findAll() {
            return new ArrayList<>();
        }
    }

    static class TestUserDAO extends UserDAO {
        private final ConcurrentHashMap<String, User> users = new ConcurrentHashMap<>();

        public TestUserDAO() {
            Bidder b1 = new Bidder("Bidder One", "bidder1@test.com", "hash1");
            b1.setId(1L);
            Bidder b2 = new Bidder("Bidder Two", "bidder2@test.com", "hash2");
            b2.setId(2L);
            users.put("bidder1@test.com", b1);
            users.put("bidder2@test.com", b2);
        }

        @Override
        public User findByEmail(String email) {
            return users.get(email);
        }

        @Override
        public User findById(Long id) {
            return users.values().stream().filter(u -> id.equals(u.getId())).findFirst().orElse(null);
        }
    }

    static class TestAutoBidDAO extends AutoBidDAO {
        @Override
        public void upsert(com.ltnc.auction.server.model.AutoBidConfig config) {
            // No-op for tests (in-memory via AuctionService's autoBidConfigs map)
        }

        @Override
        public List<com.ltnc.auction.server.model.AutoBidConfig> findByAuction(Long auctionId) {
            return new ArrayList<>();
        }

        @Override
        public void deleteByAuction(Long auctionId) {}
    }
}
