package com.ltnc.auction.server.db;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class SchemaInitializer {

    private SchemaInitializer() {}

    public static void initialize() {
        try (Connection conn = DBConnection.getConnection();
             Statement stmt = conn.createStatement()) {

            stmt.execute("""
                CREATE TABLE IF NOT EXISTS users (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    username VARCHAR(100) UNIQUE NOT NULL,
                    full_name VARCHAR(100) NOT NULL,
                    password_hash VARCHAR(255) NOT NULL,
                    role VARCHAR(20) NOT NULL
                )
                """);

            stmt.execute("""
                CREATE TABLE IF NOT EXISTS items (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    seller_id BIGINT NOT NULL,
                    seller_email VARCHAR(100) NOT NULL,
                    type VARCHAR(20) NOT NULL,
                    name VARCHAR(200) NOT NULL,
                    description VARCHAR(1000),
                    starting_bid DECIMAL(19,2) NOT NULL,
                    image_url VARCHAR(500),
                    CONSTRAINT fk_items_seller FOREIGN KEY (seller_id) REFERENCES users(id)
                )
                """);

            seedUser(conn, "Demo Bidder", "demo@gmail.com",
                    "8278ec4f4f51104d25f84e4f6f8ef3f6dd8f3481809b0a35a19df0c9da6f3f78", "BIDDER");
            seedUser(conn, "Seller One", "seller@gmail.com",
                    "34eb1e57db740f8f235a5f9f06f3779fcb22f7f0ef6fbf89fefb5227e5f4ea93", "SELLER");
            seedUser(conn, "System Admin", "admin@gmail.com",
                    "fedab9f37e2e9f9718df17d56651e697f7f3e806e3dbf0e9404ca31395dd5957", "ADMIN");

            System.out.println("[DB] Schema initialized successfully.");
        } catch (SQLException e) {
            throw new RuntimeException("Failed to initialize schema", e);
        }
    }

    private static void seedUser(Connection conn, String fullName, String email, String passwordHash, String role)
            throws SQLException {
        try (PreparedStatement check = conn.prepareStatement(
                "SELECT id FROM users WHERE username = ?")) {
            check.setString(1, email);
            try (ResultSet rs = check.executeQuery()) {
                if (rs.next()) {
                    return;
                }
            }
        }

        try (PreparedStatement insert = conn.prepareStatement(
                "INSERT INTO users (username, full_name, password_hash, role) VALUES (?, ?, ?, ?)")) {
            insert.setString(1, email);
            insert.setString(2, fullName);
            insert.setString(3, passwordHash);
            insert.setString(4, role);
            insert.executeUpdate();
        }
    }
}
