package com.ltnc.auction.server.db;

import com.ltnc.auction.server.service.PasswordUtil;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class SchemaInitializer {

    private static final Logger LOG = LoggerFactory.getLogger(SchemaInitializer.class);

    private SchemaInitializer() {}

    public static void initialize() {
        try (Connection conn = DBConnection.getConnection();
                Statement stmt = conn.createStatement()) {

            // Users table
            stmt.execute("""
                    CREATE TABLE IF NOT EXISTS users (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        username VARCHAR(100) UNIQUE,
                        full_name VARCHAR(100),
                        password_hash VARCHAR(255),
                        role VARCHAR(20),
                        is_deleted BOOLEAN DEFAULT FALSE
                    )
                    """);

            // Items table
            stmt.execute("""
                    CREATE TABLE IF NOT EXISTS items (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        seller_id BIGINT,
                        seller_email VARCHAR(100),
                        type VARCHAR(20),
                        name VARCHAR(200),
                        description VARCHAR(1000),
                        starting_bid DECIMAL(19,2),
                        image_url VARCHAR(500),
                        is_deleted BOOLEAN DEFAULT FALSE
                    )
                    """);

            // Auctions table
            stmt.execute("""
                    CREATE TABLE IF NOT EXISTS auctions (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        item_id BIGINT,
                        title VARCHAR(200),
                        description VARCHAR(1000),
                        category VARCHAR(50),
                        starting_bid DECIMAL(19,2),
                        current_bid DECIMAL(19,2),
                        start_time TIMESTAMP,
                        end_time TIMESTAMP,
                        status VARCHAR(20),
                        highest_bidder_id BIGINT,
                        winner_email VARCHAR(100),
                        seller_email VARCHAR(100),
                        image_url VARCHAR(500),
                        is_deleted BOOLEAN DEFAULT FALSE
                    )
                    """);

            // Bid transactions table
            stmt.execute("""
                    CREATE TABLE IF NOT EXISTS bid_transactions (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        auction_id BIGINT,
                        bidder_id BIGINT,
                        bidder_email VARCHAR(100),
                        bidder_name VARCHAR(100),
                        amount DECIMAL(19,2),
                        created_at TIMESTAMP
                    )
                    """);

            // Auto bid configs table
            stmt.execute("""
                    CREATE TABLE IF NOT EXISTS auto_bid_configs (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        auction_id BIGINT,
                        bidder_id BIGINT,
                        bidder_email VARCHAR(100),
                        max_bid DECIMAL(19,2),
                        increment_amount DECIMAL(19,2),
                        registered_at TIMESTAMP,
                        UNIQUE(auction_id, bidder_id)
                    )
                    """);

            stmt.execute("CREATE TABLE IF NOT EXISTS notifications (" +
                    "id BIGINT AUTO_INCREMENT PRIMARY KEY," +
                    "user_id BIGINT NOT NULL," +
                    "title VARCHAR(255) NOT NULL," +
                    "message VARCHAR(1000) NOT NULL," +
                    "type VARCHAR(50) NOT NULL," +
                    "is_read BOOLEAN DEFAULT FALSE," +
                    "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP" +
                    ")");

            stmt.execute("""
                    CREATE TABLE IF NOT EXISTS wallets (
                        user_id BIGINT PRIMARY KEY,
                        balance DECIMAL(19,2) NOT NULL DEFAULT 0,
                        reserved DECIMAL(19,2) NOT NULL DEFAULT 0,
                        updated_at TIMESTAMP
                    )
                    """);

            stmt.execute("""
                    CREATE TABLE IF NOT EXISTS wallet_transactions (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        user_id BIGINT NOT NULL,
                        type VARCHAR(20) NOT NULL,
                        amount DECIMAL(19,2) NOT NULL,
                        ref_auction_id BIGINT,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )
                    """);

            // Alter tables to add is_deleted if not present (migration)
            alterTableAddColumn(stmt, "users", "is_deleted", "BOOLEAN DEFAULT FALSE");
            alterTableAddColumn(stmt, "items", "is_deleted", "BOOLEAN DEFAULT FALSE");
            alterTableAddColumn(stmt, "auctions", "is_deleted", "BOOLEAN DEFAULT FALSE");

            // --- PERFORMANCE OPTIMIZATION: Database Indexes ---
            stmt.execute("CREATE INDEX IF NOT EXISTS idx_users_username ON users(username)");
            stmt.execute("CREATE INDEX IF NOT EXISTS idx_items_seller_email ON items(seller_email)");
            stmt.execute("CREATE INDEX IF NOT EXISTS idx_auctions_status ON auctions(status)");
            stmt.execute("CREATE INDEX IF NOT EXISTS idx_auctions_seller_email ON auctions(seller_email)");
            stmt.execute("CREATE INDEX IF NOT EXISTS idx_bid_tx_auction_id ON bid_transactions(auction_id)");
            stmt.execute("CREATE INDEX IF NOT EXISTS idx_wallet_tx_user_id ON wallet_transactions(user_id)");

            // Seed default users if not present
            seedUser(conn, "Demo Bidder", "demo@gmail.com", "Demo@123", "BIDDER");
            seedUser(conn, "Seller One", "seller@gmail.com", "Seller@123", "SELLER");
            seedUser(conn, "System Admin", "admin@gmail.com", "Admin@123", "ADMIN");

            seedWalletIfMissing(conn, "demo@gmail.com", new BigDecimal("50000.00"));
            seedWalletIfMissing(conn, "seller@gmail.com", new BigDecimal("50000.00"));
            seedWalletIfMissing(conn, "admin@gmail.com", new BigDecimal("50000.00"));

            LOG.info("Database schema initialized successfully");
        } catch (SQLException e) {
            throw new RuntimeException("Failed to initialize schema", e);
        }
    }

    private static void seedUser(Connection conn, String fullName, String email, String password, String role)
            throws SQLException {
        // Check if user already exists
        try (PreparedStatement check = conn.prepareStatement(
                "SELECT id FROM users WHERE username = ?")) {
            check.setString(1, email);
            try (ResultSet rs = check.executeQuery()) {
                if (rs.next()) {
                    return; // already exists
                }
            }
        }
        // Insert
        try (PreparedStatement insert = conn.prepareStatement(
                "INSERT INTO users (username, full_name, password_hash, role) VALUES (?, ?, ?, ?)")) {
            insert.setString(1, email);
            insert.setString(2, fullName);
            insert.setString(3, PasswordUtil.hash(password));
            insert.setString(4, role);
            insert.executeUpdate();
        }
    }

    private static void seedWalletIfMissing(Connection conn, String email, BigDecimal initialBalance)
            throws SQLException {
        Long userId = null;
        try (PreparedStatement q = conn.prepareStatement("SELECT id FROM users WHERE username = ?")) {
            q.setString(1, email);
            try (ResultSet rs = q.executeQuery()) {
                if (rs.next()) {
                    userId = rs.getLong(1);
                }
            }
        }
        if (userId == null) {
            return;
        }
        try (PreparedStatement check = conn.prepareStatement("SELECT 1 FROM wallets WHERE user_id = ?")) {
            check.setLong(1, userId);
            try (ResultSet rs = check.executeQuery()) {
                if (rs.next()) {
                    return;
                }
            }
        }
        try (PreparedStatement ins = conn.prepareStatement(
                "INSERT INTO wallets (user_id, balance, reserved, updated_at) VALUES (?, ?, 0, CURRENT_TIMESTAMP)")) {
            ins.setLong(1, userId);
            ins.setBigDecimal(2, initialBalance);
            ins.executeUpdate();
        }
    }

    private static void alterTableAddColumn(Statement stmt, String tableName, String columnName, String columnDefinition) {
        try {
            stmt.execute("ALTER TABLE " + tableName + " ADD COLUMN " + columnName + " " + columnDefinition);
            LOG.info("Added column {} to table {}", columnName, tableName);
        } catch (SQLException e) {
            // Column already exists, ignore
        }
    }
}
