package com.ltnc.auction.shared.protocol;

public enum MessageType {
    // C -> S
    PING, LOGIN, REGISTER, CREATE_ITEM, UPDATE_ITEM, DELETE_ITEM, GET_ITEMS_BY_SELLER,GET_AUCTIONS, PLACE_BID, GET_WALLET, DEPOSIT, WITHDRAW, 
    
    // S -> C
    LOGIN_RESULT, REGISTER_RESULT, CREATE_ITEM_RESULT, UPDATE_ITEM_RESULT, DELETE_ITEM_RESULT, GET_ITEMS_BY_SELLER_RESULT, AUCTION_LIST, BID_RESULT, WALLET_RESULT, DEPOSIT_RESULT, WITHDRAW_RESULT,

    // S -> C error
    ERROR;
}
