package com.ltnc.auction.shared.protocol;

public enum MessageType {
    // C→S
    PING, REGISTER, LOGIN, LOGOUT,
    GET_AUCTIONS, PLACE_BID, REGISTER_AUTO_BID,
    GET_WALLET, DEPOSIT, WITHDRAW,
    CREATE_ITEM, GET_ITEMS_BY_SELLER, UPDATE_ITEM, DELETE_ITEM,
    CREATE_AUCTION, GET_ALL_USERS, UPDATE_USER, DELETE_USER, DELETE_PRODUCT, DELETE_AUCTION, GET_BID_LOGS, GET_WALLET_TRANSACTIONS, CANCEL_AUCTION, UPDATE_AUCTION, CONFIRM_PAYMENT,
    GET_NOTIFICATIONS, MARK_NOTIFICATION_READ, MARK_ALL_NOTIFICATIONS_READ, MARK_NOTIFICATION_UNREAD,
    // S→C responses
    PONG, AUTH_RESULT, AUCTION_LIST, BID_RESULT, AUTO_BID_RESULT,
    WALLET_RESULT, DEPOSIT_RESULT, WITHDRAW_RESULT, WALLET_TRANSACTIONS_RESULT, CANCEL_AUCTION_RESULT,
    ITEM_LIST, ITEM_RESULT, USER_LIST, BID_LOG_LIST, AUCTION_CREATED,
    CREATE_AUCTION_RESULT, UPDATE_AUCTION_RESULT, CONFIRM_PAYMENT_RESULT,
    NOTIFICATIONS_RESULT,

    // S→C broadcasts
    AUCTION_UPDATE,
    ITEM_UPDATE,
    ITEM_DELETED,
    USER_CREATED,
    WALLET_UPDATE,
    AUCTION_STATE_CHANGE,
    AUCTION_DELETED,
    NEW_NOTIFICATION,
    FORCE_LOGOUT,
    ERROR
}
