package src.db;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

public class SchemaInitializer
{
    private SchemaInitializer() {};

    public static void initialize()
    {
        try (Connection conn = DBConnection.getConnection())
        {
            Statement stmt = conn.createStatement();

            // Khởi tạo bảng users
            stmt.execute("""
                    CREATE TABLE IF NOT EXISTS users (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        email VARCHAR(100) NOT NULL UNIQUE,
                        fullname VARCHAR(100) NOT NULL,
                        password_hash VARCHAR(255) NOT NULL,
                        role VARCHAR(20) NOT NULL,
                        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        CONSTRAINT chk_user_role CHECK (role IN ('ADMIN','SELLER','BIDDER'))
                    )
                    """);

            // Khởi tạo bảng items
            stmt.execute("""
                    CREATE TABLE IF NOT EXISTS items (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        seller_id BIGINT NOT NULL,
                        seller_email VARCHAR(100) NOT NULL,
                        type VARCHAR(50) NOT NULL,
                        name VARCHAR(100) NOT NULL,
                        description VARCHAR(500),
                        starting_bid DECIMAL(19,2) NOT NULL,
                        img_url VARCHAR(255),
                        created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        CONSTRAINT fk_items_seller FOREIGN KEY (seller_id) REFERENCES users(id)
                    )
                    """);
           
       
                // Auctions table
                stmt.execute("""
                    CREATE TABLE IF NOT EXISTS auctions (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    item_id BIGINT,
                    title VARCHAR(200) NOT NULL,
                    description VARCHAR(1000),
                    category VARCHAR(50),
                    starting_bid DECIMAL(19,2) NOT NULL CHECK (starting_bid >= 0),
                    current_bid DECIMAL(19,2) NOT NULL CHECK (current_bid >= 0),
                    start_time TIMESTAMP NOT NULL,
                    end_time TIMESTAMP NOT NULL,
                    status VARCHAR(20) NOT NULL,
                    highest_bidder_id BIGINT,
                    winner_email VARCHAR(100),
                    seller_email VARCHAR(100),
                    image_url VARCHAR(500),
                    CONSTRAINT fk_auctions_item FOREIGN KEY (item_id) REFERENCES items(id),
                    CONSTRAINT fk_auctions_highest_bidder FOREIGN KEY (highest_bidder_id) REFERENCES users(id),
                    CONSTRAINT chk_auction_status CHECK (status IN ('OPEN', 'CLOSED', 'ENDED'))
                )
                        
                        """);
                    
                
             // Bid transactions table
            stmt.execute("""
                CREATE TABLE IF NOT EXISTS bid_transactions (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    auction_id BIGINT NOT NULL,
                    bidder_id BIGINT NOT NULL,
                    bidder_email VARCHAR(100) NOT NULL,
                    bidder_name VARCHAR(100),
                    amount DECIMAL(19,2) NOT NULL CHECK (amount > 0),
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT fk_bid_tx_auction FOREIGN KEY (auction_id) REFERENCES auctions(id),
                    CONSTRAINT fk_bid_tx_bidder FOREIGN KEY (bidder_id) REFERENCES users(id)
                )
                """);
            // Wallets table
            stmt.execute("""
                CREATE TABLE IF NOT EXISTS wallets (
                    user_id BIGINT PRIMARY KEY,
                    balance DECIMAL(19,2) NOT NULL DEFAULT 0 CHECK (balance >= 0),
                    reserved DECIMAL(19,2) NOT NULL DEFAULT 0 CHECK (reserved >= 0),
                    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT fk_wallets_user FOREIGN KEY (user_id) REFERENCES users(id)
                )
                """);

            // Wallet transactions table
            stmt.execute("""
                CREATE TABLE IF NOT EXISTS wallet_transactions (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id BIGINT NOT NULL,
                    type VARCHAR(50) NOT NULL,
                    amount DECIMAL(19,2) NOT NULL CHECK (amount > 0),
                    ref_auction_id BIGINT,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT fk_wallet_tx_user FOREIGN KEY (user_id) REFERENCES users(id),
                    CONSTRAINT fk_wallet_tx_auction FOREIGN KEY (ref_auction_id) REFERENCES auctions(id)
                ) 
                """);

            System.out.println("Schema initialized successfully");
        } catch (SQLException e) {
            System.err.println("Error initializing schema: " + e.getMessage());
            e.printStackTrace();
        }
    }
    public static void main(String[] args)
    {
        SchemaInitializer.initialize();
    }
}
